#!/bin/bash

# Set default editor to vim and terminal to alacritty
sed -i '/EDITOR=/d;/TERMINAL=/d' /etc/environment
printf 'EDITOR=vim\nTERMINAL=alacritty\n' | tee -a /etc/environment > /dev/null

# Disable PC Speaker
echo 'blacklist pcspkr' | tee /etc/modprobe.d/nobeep.conf > /dev/null

# Enable lightdm
systemctl enable lightdm.service

