#!/bin/bash
set -e

if [ -z "$1" ]; then
  echo "Supply swapfile size in GiB"
  exit 1
fi

sudo swapoff /swapfile
sudo rm /swapfile

sudo dd if=/dev/zero of=/swapfile bs=1G count="$1" status=progress
sudo chmod 0600 /swapfile
sudo mkswap -U clear /swapfile
sudo swapon /swapfile

if [ -z "$(grep swapfile /etc/fstab)" ]; then
  echo "Adding entry to fstab for the swap file:"
  echo "/swapfile swap swap defaults 0 0" | sudo tee --append /etc/fstab
fi
