#!/bin/bash
set -e

# Mount hard drive
sudo mkdir -p /media/hdd
sudo chown root:root /media
sudo chown "$user":"$user" /media/hdd
sudo chmod u=rwx,g=rx,o=rx /media
chmod u=rwx,g=rx,o= /media/hdd
if ! grep -q 'ea862cc9-c5b3-4c8a-a07b-ece92b9a649a' /etc/fstab; then
  echo 'UUID=ea862cc9-c5b3-4c8a-a07b-ece92b9a649a /media/hdd     ext4    defaults   0 2' | sudo tee -a /etc/fstab > /dev/null
fi
sudo mount -a

# Create hard drive symlinks
for d in Desktop Documents Downloads Music Pictures Public Templates Videos; do
  rmdir ~/$d
  ln -s /media/hdd/$d ~/$d
done
