#!/bin/bash
set -e

# Install packages
sudo pacman -Syu
yay -S --needed $(cat packages.txt)

# Disable PC Speaker
echo 'blacklist pcspkr' | sudo tee /etc/modprobe.d/nobeep.conf > /dev/null

# Set systemd-boot timeout to 0
sudo sed -i 's/timeout.*/timeout 0/' /efi/loader/loader.conf

# Add 'quiet spash' to kernel cmdline
sudo mkdir -p /etc/kernel
if [ -s /etc/kernel/cmdline ] && ! [ -s /etc/kernel/cmdline.backup ]; then
  sudo mv /etc/kernel/cmdline /etc/kernel/cmdline.backup
fi
echo "quiet splash" | sudo tee /etc/kernel/cmdline > /dev/null

# Enable lightdm
sudo systemctl enable lightdm.service

# Power button suspends
sudo mkdir -p /etc/systemd/logind.conf.d
printf '[Login]\nHandlePowerKey=suspend\n' | sudo tee /etc/systemd/logind.conf.d/powerbutton.conf > /dev/null
sudo systemctl kill -s HUP systemd-logind

# Create dwm.desktop file
sudo mkdir -p /usr/share/xsessions
sudo cp dwm.desktop /usr/share/xsessions
sudo ln -s /usr/share/xsessions/dwm.desktop /usr/share/xsessions/default.desktop

# NumLock on by default
sudo sed -i 's/#greeter-setup-script=/greeter-setup-script=\/usr\/bin\/numlockx on/' /etc/lightdm/lightdm.conf

# Disable mouse acceleration
echo 'Section "InputClass"
	Identifier "My Mouse"
	MatchIsPointer "yes"
	Option "AccelerationProfile" "-1"
	Option "AccelerationScheme" "none"
	Option "AccelSpeed" "-1"
EndSection' | sudo tee /etc/X11/xorg.conf.d/50-mouse-acceleration.conf > /dev/null

# Set default editor to neovim and terminal to alacritty
sudo sed -i '/VISUAL=/d;/EDITOR=/d;/TERMINAL=/d' /etc/environment
printf 'VISUAL=nvim\nEDITOR=nvim\nTERMINAL=alacritty\n' | sudo tee -a /etc/environment > /dev/null

# Create nvim.desktop file and set as default for opening text files
mkdir -p ~/.local/share/applications
cp nvim.desktop ~/.local/share/applications/
