#!/bin/bash
set -e

# Install packages
sudo pacman -Syu
yay -S --needed $(cat packages.txt)

# Disable PC Speaker
echo 'blacklist pcspkr' | sudo tee /etc/modprobe.d/nobeep.conf > /dev/null

# Enable lightdm
sudo systemctl enable lightdm.service

# Power button suspends
sudo mkdir -p /etc/systemd/logind.conf.d
printf '[Login]\nHandlePowerKey=suspend\n' | sudo tee /etc/systemd/logind.conf.d/powerbutton.conf > /dev/null
sudo systemctl kill -s HUP systemd-logind

# Create dwm.desktop file
sudo mkdir -p /usr/share/xsessions
sudo cp dwm.desktop /usr/share/xsessions
sudo ln -s /usr/share/xsessions/dwm.desktop /usr/share/xsessions/default.desktop

# NumLock on by default
sudo sed -i 's/#greeter-setup-script=/greeter-setup-script=\/usr\/bin\/numlockx on/' /etc/lightdm/lightdm.conf

# Disable mouse acceleration
echo 'Section "InputClass"
	Identifier "My Mouse"
	Driver "libinput"
	MatchProduct "Mouse"
	Option "AccelProfile" "flat"
	Option "AccelSpeed" "-0.6"
EndSection' | sudo tee /etc/X11/xorg.conf.d/50-mouse-acceleration.conf > /dev/null

# Set keyboard layout
sudo localectl set-x11-keymap gb "" "" caps:escape

# Set default editor to neovim and terminal to alacritty
sudo sed -i '/VISUAL=/d;/EDITOR=/d;/TERMINAL=/d' /etc/environment
printf 'VISUAL=nvim\nEDITOR=nvim\nTERMINAL=alacritty\n' | sudo tee -a /etc/environment > /dev/null

# Create nvim.desktop file and set as default for opening text files
mkdir -p ~/.local/share/applications
cp nvim.desktop ~/.local/share/applications/

# Create systemd sleep hook to lock when suspending
echo '[Unit]
Description=User suspend actions
Before=sleep.target

[Service]
User=%I
Type=forking
Environment=DISPLAY=:0
ExecStart=/usr/bin/i3lock-fancy
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sleep.target' | sudo tee /etc/systemd/system/suspend@.service > /dev/null

# Copy wallpaper to Pictures
cp wallpaper.png ~/Pictures/
