#!/bin/bash
set -e

# Install packages
sudo pacman -Syu
yay -S --needed $(cat packages.txt)

# Set default editor to vim and terminal to alacritty
sudo sed -i '/EDITOR=/d;/TERMINAL=/d' /etc/environment
printf 'EDITOR=vim\nTERMINAL=alacritty\n' | sudo tee -a /etc/environment > /dev/null

# Disable PC Speaker
echo 'blacklist pcspkr' | sudo tee /etc/modprobe.d/nobeep.conf > /dev/null

# Enable lightdm
sudo systemctl enable lightdm.service

# Disable mouse acceleration
echo 'Section "InputClass"
	Identifier "My Mouse"
	MatchIsPointer "yes"
	Option "AccelerationProfile" "-1"
	Option "AccelerationScheme" "none"
	Option "AccelSpeed" "-1"
EndSection' | sudo tee /etc/X11/xorg.conf.d/50-mouse-acceleration.conf > /dev/null

# NumLock on by default
sudo sed -i 's/#greeter-setup-script=/greeter-setup-script=\/usr\/bin\/numlockx on/' /etc/lightdm/lightdm.conf

# Power button suspends
sudo mkdir -p /etc/systemd/logind.conf.d
printf '[Login]\nHandlePowerKey=suspend\n' | sudo tee /etc/systemd/logind.conf.d/powerbutton.conf > /dev/null
sudo systemctl kill -s HUP systemd-logind

# Set firefox as the default for opening links, html files and pdfs
xdg-mime default firefox.desktop 'x-scheme-handler/http'
xdg-mime default firefox.desktop 'x-scheme-handler/https'
xdg-mime default firefox.desktop 'text/html'
xdg-mime default firefox.desktop 'application/pdf'
